version: "3"

services:
  webserver:
    build:
      context: ./lamp/bin/webserver
      args:
        USER_ID: ${USER_ID:-root}
        GROUP_ID: ${GROUP_ID:-root}
    container_name: '${PROJECT_NAME}-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ../:/var/www/html
      - ./lamp/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./lamp/config/vhosts:/etc/apache2/sites-enabled
      - ./lamp/logs/apache2:/var/log/apache2
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/${DOCUMENT_ROOT:-web}
    networks:
      default:
        aliases:
          - ${PROJECT_NAME}.localhost

  mysql:
    build: ./lamp/bin/mysql
    container_name: '${PROJECT_NAME}-5.7-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ./lamp/data/mysql:/var/lib/mysql
      - ./lamp/logs/mysql:/var/log/mysql
      - ./lamp/bin/mysql/init.sql:/data/application/init.sql
    command: --max_allowed_packet=32505856 --init-file /data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${PROJECT_NAME}-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions

  redis:
    container_name: '${PROJECT_NAME}-redis'
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  default:
